Using cuda device
/home/kpatherya3/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Traceback (most recent call last):
  File "mfrl_scratch.py", line 141, in <module>
    model = train_policy(
  File "mfrl_scratch.py", line 81, in train_policy
    model = SAC(
  File "/home/kpatherya3/.local/lib/python3.8/site-packages/stable_baselines3/sac/sac.py", line 157, in __init__
    self._setup_model()
  File "/home/kpatherya3/.local/lib/python3.8/site-packages/stable_baselines3/sac/sac.py", line 160, in _setup_model
    super()._setup_model()
  File "/home/kpatherya3/.local/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 189, in _setup_model
    self.replay_buffer = self.replay_buffer_class(
TypeError: __init__() got an unexpected keyword argument 'max_episode_length'
Traceback (most recent call last):
  File "mfrl_scratch.py", line 141, in <module>
    model = train_policy(
  File "mfrl_scratch.py", line 81, in train_policy
    model = SAC(
  File "/home/kpatherya3/.local/lib/python3.8/site-packages/stable_baselines3/sac/sac.py", line 157, in __init__
    self._setup_model()
  File "/home/kpatherya3/.local/lib/python3.8/site-packages/stable_baselines3/sac/sac.py", line 160, in _setup_model
    super()._setup_model()
  File "/home/kpatherya3/.local/lib/python3.8/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 189, in _setup_model
    self.replay_buffer = self.replay_buffer_class(
TypeError: __init__() got an unexpected keyword argument 'max_episode_length'
